version: '3.8'

services:
  redis:
    image: 'redis:7'
    container_name: 'redis'
    ports:
      - 6379:6379

  email-ingestion-service:
    build:
      context: .
      dockerfile: email-ingestion-service/Dockerfile
    container_name: 'email-ingestion-service'
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - D:/Jobs/Assona/claims:/app/storage


  email-processing-worker:
    build:
      context: .
      dockerfile: email-processing-worker/Dockerfile
    container_name: 'email-processing-worker'
    depends_on:
      - redis
    env_file:
      - .env

  monitoring-dashboard:
    build:
      context: .
      dockerfile: monitoring-dashboard/Dockerfile
    container_name: 'monitoring-dashboard'
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  prometheus:
    image: 'prom/prometheus:v3.5.0'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - email-ingestion-service

  grafana:
    image: 'grafana/grafana:12.1.0'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  grafana_data: {}