{
 "title": "Claims Handler",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ingestion Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(emails_ingestion_latency_sum[5m]) / rate(emails_ingestion_latency_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Ingestion Queue ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ingestion_queue_length", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Ingested Emails",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emails_ingested_total", "legendFormat": "__auto" }
   ]
  }
 ]
}